### ISSUE TITLE
Label is not connected with checkbox

### ISSUE THREAD

**Issue by masi** [01-Scripts/2Click-Iframe-Privacy#12]
It should be:
`<label><input type="checkbox" name="remind-'xxx'">Foobar</label>`

It's valid HTML that the label encompasses the field it is assign to. Otherwise the checkbox needs a (unique) id that is referred in the for-attribute of the label.

**Comment by 01-Scripts** [comment]
Thanks, I will check.

**Comment by designchris** [comment]
Just came here to post about this and found this thread.
+1
