### ISSUE TITLE
data-attribut statt title verwenden

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [01-Scripts/2Click-Iframe-Privacy#2]
der Pfad zum iFrame sollte besser nicht im title-Attribut stecken, sondern in einem eigenen data-Attribut, z.B.

`data-src="https://meine-url.de"`

Siehe: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

**Comment by 01-Scripts** [comment]
Hi,

danke für den Hinweis. Wenn ich mich richtig erinnere hatte die Nutzung des data-Attributs während der Implementierung einen gravierenden Nachteil. Ich versuche das bei Gelegenheit nochmal zu reproduzieren warum meine Entscheidung für die erste Implementierung dann auf das title-Attribut gefallen ist.  

In jedem Fall vielen Dank für dein Feedback!

**Comment by stephangrass** [comment]
Mit data-src klappt das.
Musst dann nur

`selector[x].title`

durch 

`selector[x].getAttribute("data-src");`

ersetzen.
Allerdings ist bei Deinem Script fraglich, ob man einfach so ein Cookie setzen darf.

**Comment by AWqxKAWERbXo** [comment]
> Allerdings ist bei Deinem Script fraglich, ob man einfach so ein Cookie setzen darf.

Darf man auch nach der DSGVO, wenn technisch notwendig, so wie hier.

**Comment by stephangrass** [comment]
> Darf man auch nach der DSGVO, wenn technisch notwendig, so wie hier.

Technisch notwendig ist das aber nicht. 
Und wenn doch, dann aber nur als Session-Cookie ...

**Comment by 01-Scripts** [comment]
Hallo @alexplusde & @stephangrass 

vielen Dank für euer Feedback. Den Grund warum ich initial auf das title-Attribut statt auf data-src gesetzt habe, konnte ich nicht (mehr) reproduzieren. Ich plane daher für die nächste Version das Script entsprechend anzupassen.

Bzgl. der Cookie-Diskussion:  
Hier ist meiner Ansicht nach der jeweils nutzende Webmaster gefragt das Script entsprechend zu konfigurieren (Stichwort: noCookie-Option) oder entsprechend in seine jeweilige Cookie-Lösung mit aufzunehmen.  
Es stimmt allerdings, dass man für den Cookie ein Session-Cookie setzen könnte.

Was meint ihr: Das Cookie mit Lifetime durch ein Session-Cookie ersetzen oder via Option beides ermöglichen?

Danke für euer Feedback,  
Michael

**Comment by AWqxKAWERbXo** [comment]
Ein Parameter fände ich sinnvoll, da das Verhalten bewusst gewählt werden sollte und nicht festgeschrieben werden müsste.

**Comment by stephangrass** [comment]
Perfekt wäre es, wenn dem User eine Checkbox angeboten würde, über dass er seine Entscheidung in einem Session-Cookie speichern kann. Als Label für die Checkbox so etwas wie: Videos während meines Besuchs nicht mehr blockieren.

**Comment by urbanGorilla76** [comment]
Moin moin zusammen,
ich stimme da @stephangrass zu und würde mich sehr über eine Checkbox freuen. 
An dieser Stelle auch ein Dankeschön für das Script. Setzte ich sehr gern ein und funktioniert super!
Viele Grüße
Alex

**Comment by 01-Scripts** [comment]
Hallo,

die weitere Diskussion zur Verbesserung der Cookie-Implementierung bitte in #4 führen. Danke.

Eine aktuelle Testversion ist hier zu finden: https://github.com/01-Scripts/2Click-Iframe-Privacy/tree/new-features

**Comment by AWqxKAWERbXo** [comment]
Hey @01-Scripts, habe es mal getestet. Passt gut!
