### ISSUE TITLE
Cookie-Nutzung verbessern

### ISSUE THREAD

**Issue by 01-Scripts** [01-Scripts/2Click-Iframe-Privacy#4]
Original Dikussion startete in #2

Bzgl. der Cookie-Diskussion:  
Hier ist meiner Ansicht nach der jeweils nutzende Webmaster gefragt das Script entsprechend zu konfigurieren (Stichwort: noCookie-Option) oder entsprechend in seine jeweilige Cookie-Lösung mit aufzunehmen.  
Es stimmt allerdings, dass man für den Cookie ein Session-Cookie setzen könnte.

Was meint ihr: Das Cookie mit Lifetime durch ein Session-Cookie ersetzen oder via Option beides ermöglichen?

Danke für euer Feedback,  
Michael

_Originally posted by @01-Scripts in https://github.com/01-Scripts/2Click-Iframe-Privacy/issues/2#issuecomment-547508335_

**Comment by 01-Scripts** [comment]
@alexplusde & @stephangrass & @urbanGorilla76

Ich habe eine Testversion v0.2.0 erstellt. Diese enthält:

- Session-Cookie/"normales" Cookie via Config
- Checkbox für den User ob ein Cookie gesetzt werden soll oder nicht
- Umkehrung der config-Logik. Aus `noCookies: false` wird `enableCookies: true`

Ich würde mich freuen wenn ihr einen Blick drauf werft:  
https://github.com/01-Scripts/2Click-Iframe-Privacy/tree/new-features

Changes:  
https://github.com/01-Scripts/2Click-Iframe-Privacy/compare/new-features

**Achtung:**  
Auch der Selector hat sich wie in #2 besprochen, geändert. Statt `title=` wird `src-data=` genutzt!

**Comment by stephangrass** [comment]
Hi,
ok, sieht auf der ersten Blick OK aus.

Eins noch: Du setzt die Breite und Höhe des Wrappers anhand der Größe des iFrames.
1. Muss das überhaupt sein?
Wenn ja:
2. Da iFrames ja in der Regel die Breite und Höhe angegeben wird, würde ich, wenn vorhanden, diese nehmen. Ich setzte z.B. bei Maps die Breite oft auf 100%, damit die ganze  Sache responsive ist.
3. Vielleicht auch auf das Resize-Event reagieren und dann die Breite und Höhe immer neu setzen.

**Comment by stephangrass** [comment]
Und es sollten alle Texte konfigurierbar sein, denke ich mal.

**Comment by AWqxKAWERbXo** [comment]
@stephangrass das sind an sich alles separate neue Issues. 

@01-Scripts mal schauen, ob ich die Tage dazu komme, noch ein paar PRs beizusteuern.

**Comment by 01-Scripts** [comment]
@alexplusde 

Vielen Dank für die PRs. Die Änderungen sehen auf den ersten Blick sehr gut aus.  
Ich werde versuchen die PRs in den nächsten Tagen anzunehmen und jeweils die Dokumentation/Readme noch entsprechend nach zu ziehen.

MfG,  
Michael

**Comment by 01-Scripts** [comment]
Hallo zusammen,

ich habe alle PRs angenommen und die Dokumentation in der readme-Datei entsprechend angepasst.  
Eine Vorab-Version v0.3.0 steht hier im Branch zum Testen zur Verfügung:  
https://github.com/01-Scripts/2Click-Iframe-Privacy/tree/new-features

Ich würde mich auch freuen wenn ihr über die Readme.md-Datei noch drüber lesen könntet.

MfG,  
Michael

**Comment by 01-Scripts** [comment]
Fixed with v0.3.0: https://github.com/01-Scripts/2Click-Iframe-Privacy/releases/tag/v0.3.0
